import type { MarathonQuestion } from "../../types/train"

// PLACEHOLDER CONTENT — replace with uploaded questions later.
//
// This is a temporary, hand-written pool so the Train marathon can run before
// the real question backend exists. Questions are deliberately BROAD general
// knowledge (geography, basic science, everyday logic, common history, simple
// math, language) and are NOT tied to any post format or topic feed. The
// `topic` tag is coarse and informational only; the marathon never filters on
// it. Roughly 8 questions per difficulty (1/2/3), 24 total.
//
// Questions come in two kinds (see mobile/src/types/train.ts): the default
// multiple-choice (options + answerIndex) and `kind: "numeric"`, whose answer is
// a single number the player dials in on a slider. Numeric questions carry their
// own slider limits (min/max), snap step, and optional unit.
//
// The answer (answerIndex / answerValue) is included here only because this is
// the mock phase; see the note at the top of mobile/src/types/train.ts.

export const mockQuestions: MarathonQuestion[] = [
  // -------- Difficulty 1 (opponent rating 800): easy, near-universal --------
  {
    id: "geo-continents",
    kind: "numeric",
    prompt: "How many continents are there on Earth?",
    answerValue: 7,
    min: 1,
    max: 12,
    step: 1,
    difficulty: 1,
    explanation: "By the common model: Africa, Antarctica, Asia, Europe, North America, Oceania, South America.",
    topic: "geography",
  },
  {
    id: "sci-water-state",
    kind: "numeric",
    prompt: "At sea level, water boils at roughly what temperature?",
    answerValue: 100,
    min: 0,
    max: 200,
    step: 5,
    unit: " C",
    difficulty: 1,
    explanation: "Pure water boils at 100 C (212 F) at standard atmospheric pressure.",
    topic: "science",
  },
  {
    id: "math-half-of-50",
    kind: "numeric",
    prompt: "What is half of 50?",
    answerValue: 25,
    min: 0,
    max: 100,
    step: 1,
    difficulty: 1,
    explanation: "50 divided by 2 is 25.",
    topic: "math",
  },
  {
    id: "lang-plural-mouse",
    prompt: "What is the plural of 'mouse' (the animal)?",
    options: ["Mouses", "Mice", "Mouse", "Meese"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "'Mouse' has the irregular plural 'mice'.",
    topic: "language",
  },
  {
    id: "geo-sun-rise",
    prompt: "In which direction does the Sun rise?",
    options: ["North", "South", "East", "West"],
    answerIndex: 2,
    difficulty: 1,
    explanation: "The Sun rises in the east and sets in the west.",
    topic: "everyday",
  },
  {
    id: "sci-bee-makes",
    prompt: "Which of these do bees make?",
    options: ["Milk", "Honey", "Silk", "Wax paper"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Bees produce honey from flower nectar.",
    topic: "science",
  },
  {
    id: "logic-days-week",
    kind: "numeric",
    prompt: "How many days are there in a week?",
    answerValue: 7,
    min: 1,
    max: 14,
    step: 1,
    difficulty: 1,
    explanation: "A week has seven days.",
    topic: "everyday",
  },
  {
    id: "color-mix-primary",
    prompt: "Which of these is a primary color of light?",
    options: ["Brown", "Red", "Pink", "Gray"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "The additive primary colors of light are red, green, and blue.",
    topic: "science",
  },

  // -------- Difficulty 2 (opponent rating 1000): moderate general knowledge --------
  {
    id: "geo-capital-australia",
    prompt: "What is the capital of Australia?",
    options: ["Sydney", "Melbourne", "Canberra", "Perth"],
    answerIndex: 2,
    difficulty: 2,
    explanation: "Canberra is the capital, though Sydney and Melbourne are larger.",
    topic: "geography",
  },
  {
    id: "sci-planet-red",
    prompt: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Mercury"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Mars looks red due to iron oxide (rust) on its surface.",
    topic: "science",
  },
  {
    id: "hist-ww2-end",
    kind: "numeric",
    prompt: "In which year did World War II end?",
    answerValue: 1945,
    min: 1930,
    max: 1960,
    step: 1,
    difficulty: 2,
    explanation: "World War II ended in 1945.",
    topic: "history",
  },
  {
    id: "math-percent-of-200",
    kind: "numeric",
    prompt: "What is 15% of 200?",
    answerValue: 30,
    min: 0,
    max: 100,
    step: 5,
    difficulty: 2,
    explanation: "15% of 200 is 0.15 x 200 = 30.",
    topic: "math",
  },
  {
    id: "lang-synonym-rapid",
    prompt: "Which word is closest in meaning to 'rapid'?",
    options: ["Quiet", "Quick", "Heavy", "Bright"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "'Rapid' means fast or quick.",
    topic: "language",
  },
  {
    id: "sci-largest-organ",
    prompt: "What is the largest organ of the human body?",
    options: ["Liver", "Brain", "Skin", "Heart"],
    answerIndex: 2,
    difficulty: 2,
    explanation: "The skin is the body's largest organ by surface area and weight.",
    topic: "science",
  },
  {
    id: "geo-longest-river",
    prompt: "Which river is generally considered the longest in the world?",
    options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "The Nile is traditionally listed as the longest river, though the Amazon is close and debated.",
    topic: "geography",
  },
  {
    id: "logic-next-even",
    prompt: "What is the next number in the sequence 2, 4, 6, 8, ...?",
    options: ["9", "10", "12", "16"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "The sequence counts up by 2, so 8 + 2 = 10.",
    topic: "logic",
  },

  // -------- Difficulty 3 (opponent rating 1200): harder general knowledge --------
  {
    id: "sci-speed-of-light",
    prompt: "The speed of light in a vacuum is closest to:",
    options: ["300 km/s", "3,000 km/s", "300,000 km/s", "3,000,000 km/s"],
    answerIndex: 2,
    difficulty: 3,
    explanation: "Light travels at about 299,792 km/s, roughly 300,000 km/s.",
    topic: "science",
  },
  {
    id: "hist-french-revolution",
    kind: "numeric",
    prompt: "The French Revolution began in which year?",
    answerValue: 1789,
    min: 1700,
    max: 1850,
    step: 1,
    difficulty: 3,
    explanation: "The French Revolution began in 1789 with the storming of the Bastille.",
    topic: "history",
  },
  {
    id: "math-prime-check",
    prompt: "Which of these numbers is prime?",
    options: ["21", "27", "29", "33"],
    answerIndex: 2,
    difficulty: 3,
    explanation: "29 has no divisors other than 1 and itself; the others are divisible by 3.",
    topic: "math",
  },
  {
    id: "sci-element-symbol-na",
    prompt: "In chemistry, what element does the symbol 'Na' represent?",
    options: ["Nitrogen", "Sodium", "Nickel", "Neon"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "'Na' comes from the Latin 'natrium', meaning sodium.",
    topic: "science",
  },
  {
    id: "geo-country-most-population",
    prompt: "As of the 2020s, which country has the largest population?",
    options: ["China", "United States", "India", "Indonesia"],
    answerIndex: 2,
    difficulty: 3,
    explanation: "India overtook China as the most populous country in the early 2020s.",
    topic: "geography",
  },
  {
    id: "lang-antonym-scarce",
    prompt: "Which word is the opposite of 'scarce'?",
    options: ["Rare", "Plentiful", "Hidden", "Costly"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "'Scarce' means in short supply; its opposite is 'plentiful'.",
    topic: "language",
  },
  {
    id: "sci-photosynthesis-gas",
    prompt: "During photosynthesis, plants primarily release which gas?",
    options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
    answerIndex: 2,
    difficulty: 3,
    explanation: "Plants take in carbon dioxide and release oxygen during photosynthesis.",
    topic: "science",
  },
  {
    id: "logic-clock-angle",
    kind: "numeric",
    prompt: "At 3:00, what is the angle (in degrees) between the hour and minute hands of a clock?",
    answerValue: 90,
    min: 0,
    max: 180,
    step: 15,
    difficulty: 3,
    explanation: "At 3:00 the minute hand points to 12 and the hour hand to 3, a quarter turn (90 degrees) apart.",
    topic: "logic",
  },
]
