// Regenerates the off-script build inputs for the Plexive design-sync import.
// Plexive is a Next.js app, not a component library, so the converter cannot
// build it the normal way (no dist/, default exports, Tailwind v4 utilities).
// This script produces what the converter's `--entry` and `cfg.cssEntry` need:
//
//   build/process-shim.mjs    sets globalThis.process before component modules
//                             load, so Avatar's top-level process.env read does
//                             not crash the IIFE bundle in the browser.
//   build/entry.mjs           named re-export barrel of every component's
//                             default export (esbuild's `export *` synth-entry
//                             cannot see default exports).
//   build/tw-input.css        globals.css with explicit @source (the previews
//                             dir is gitignored, so Tailwind auto-detect misses
//                             it) — drives the compile below.
//   build/styles.compiled.css Tailwind v4 compiled output (tokens + component
//                             classes + used utilities) prefixed with the brand
//                             @font-face block. This is cfg.cssEntry.
//   build/fonts/*.woff2       Newsreader / Source Sans 3 / Geist Mono, the three
//                             families globals.css references via --font-* vars.
//
// Run from the frontend package root:  node .design-sync/build-inputs.mjs
// Add --force-fonts to re-download fonts that already exist on disk.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..'); // frontend/
const BUILD = join(ROOT, '.design-sync', 'build');
const FONTS = join(BUILD, 'fonts');
const FORCE_FONTS = process.argv.includes('--force-fonts');

mkdirSync(FONTS, { recursive: true });

// ── 1. process shim (evaluated first by entry.mjs's leading import) ──────────
writeFileSync(
  join(BUILD, 'process-shim.mjs'),
  '// Injected by .design-sync/build-inputs.mjs. The bundle runs in the browser\n' +
    '// where `process` is undefined; Avatar reads process.env at module load.\n' +
    'globalThis.process = globalThis.process || { env: {} };\n' +
    'if (!globalThis.process.env) globalThis.process.env = {};\n',
);

// ── 2. barrel entry: named re-export of each default export ──────────────────
const cfg = JSON.parse(readFileSync(join(ROOT, '.design-sync', 'config.json'), 'utf8'));
const map = cfg.componentSrcMap ?? {};
const names = Object.keys(map).sort();
let barrel = '// Generated by .design-sync/build-inputs.mjs — do not edit by hand.\n';
barrel += "import './process-shim.mjs';\n\n";
for (const name of names) {
  // map paths are frontend-relative; entry.mjs lives in .design-sync/build/
  barrel += `export { default as ${name} } from '../../${map[name].replace(/\\/g, '/')}';\n`;
}
writeFileSync(join(BUILD, 'entry.mjs'), barrel);
console.log(`entry.mjs: ${names.length} components`);

// ── 3. tw-input.css: globals.css with explicit @source ───────────────────────
let globals = readFileSync(join(ROOT, 'src', 'app', 'globals.css'), 'utf8');
globals = globals.replace(/@import\s+["']tailwindcss["'];?\s*/, '');
const twInput =
  '@import "tailwindcss";\n' +
  '@source "../../src";\n' + // catches utility strings in formats.ts etc., not just components
  '@source "../previews";\n' + // authored preview cards (gitignored, so not auto-detected)
  globals;
writeFileSync(join(BUILD, 'tw-input.css'), twInput);

// ── 4. compile Tailwind, prepend the brand @font-face block ──────────────────
const twInputPath = join(BUILD, 'tw-input.css');
const compiled = await postcss([tailwindcss()]).process(twInput, {
  from: twInputPath,
  to: join(BUILD, 'styles.compiled.css'),
});
const fontBlock = `/* Plexive brand fonts — shipped so designs render in the real type, not a
   fallback. globals.css maps --font-serif/sans/mono to these via @theme. */
@font-face { font-family: "Newsreader"; font-style: normal; font-weight: 200 800; font-display: swap; src: url("./fonts/newsreader.woff2") format("woff2"); }
@font-face { font-family: "Source Sans 3"; font-style: normal; font-weight: 200 900; font-display: swap; src: url("./fonts/source-sans-3.woff2") format("woff2"); }
@font-face { font-family: "Geist Mono"; font-style: normal; font-weight: 100 900; font-display: swap; src: url("./fonts/geist-mono.woff2") format("woff2"); }
:root {
  --font-newsreader: "Newsreader", Georgia, "Times New Roman", serif;
  --font-source-sans: "Source Sans 3", system-ui, -apple-system, "Segoe UI", sans-serif;
  --font-geist-mono: "Geist Mono", ui-monospace, "SF Mono", Menlo, monospace;
}
`;
// KaTeX stylesheet + fonts so MathText (and the math sections) typeset real
// LaTeX. Ship only the woff2 src (drop the woff/ttf fallbacks so nothing
// dangles); copy the 20 woff2 faces next to the brand fonts.
let katexCss = '';
const katexCssSrc = join(ROOT, 'node_modules', 'katex', 'dist', 'katex.min.css');
const katexFontDir = join(ROOT, 'node_modules', 'katex', 'dist', 'fonts');
if (existsSync(katexCssSrc)) {
  katexCss = readFileSync(katexCssSrc, 'utf8')
    .replace(/,url\(fonts\/[^)]*\.woff\)\s*format\("woff"\)/g, '')
    .replace(/,url\(fonts\/[^)]*\.ttf\)\s*format\("truetype"\)/g, '');
  for (const f of readdirSync(katexFontDir)) {
    if (f.endsWith('.woff2')) writeFileSync(join(FONTS, f), readFileSync(join(katexFontDir, f)));
  }
  katexCss = '\n/* KaTeX math typesetting (woff2 faces copied to ./fonts/) */\n' + katexCss;
}

writeFileSync(join(BUILD, 'styles.compiled.css'), fontBlock + '\n' + compiled.css + katexCss);
console.log(`styles.compiled.css: ${(fontBlock.length + compiled.css.length + katexCss.length)} bytes (katex: ${katexCss ? 'yes' : 'no'})`);

// ── 5. fonts ─────────────────────────────────────────────────────────────────
const FONT_URLS = {
  'newsreader.woff2': 'https://cdn.jsdelivr.net/fontsource/fonts/newsreader:vf@latest/latin-wght-normal.woff2',
  'source-sans-3.woff2': 'https://cdn.jsdelivr.net/fontsource/fonts/source-sans-3:vf@latest/latin-wght-normal.woff2',
  'geist-mono.woff2': 'https://cdn.jsdelivr.net/fontsource/fonts/geist-mono:vf@latest/latin-wght-normal.woff2',
};
for (const [file, url] of Object.entries(FONT_URLS)) {
  const dest = join(FONTS, file);
  if (existsSync(dest) && !FORCE_FONTS) {
    console.log(`fonts/${file}: present (skip)`);
    continue;
  }
  const r = await fetch(url);
  if (!r.ok) throw new Error(`font fetch ${file} failed: ${r.status} ${url}`);
  writeFileSync(dest, Buffer.from(await r.arrayBuffer()));
  console.log(`fonts/${file}: downloaded`);
}

// cleanup scratch from earlier probes if present
try { rmSync(join(BUILD, '_test.css')); } catch {}
console.log('build-inputs done.');
